# The URL the site will be built for
base_url = "https://taiwanstandsalone.com"
theme = "juice"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "inspired-github"

[extra]
# Put all your custom variables here
juice_logo_path = "juice.svg"
juice_logo_name = "Free Taiwan"
juice_extra_menu = [
    { title = "Github", link = "https://github.com/DefeatCCPNow/FreeTaiwanNation }
]
# Add page titles here to exclude them from the nav section (case sensitive)
juice_exclude_menu = [
    "howoverthrowccp", "whyoverthrowccp"
]
repository_url = "https://github.com/DefeatCCPNow/FreeTaiwanNation"
site_title = "Free Taiwan"
